### ISSUE TITLE
[Feature Request] Pathfinder 2e Compatability

### ISSUE THREAD

**Issue by pearcebasmanm** [HadaIonut/Foundry-mgl#11]
It wouldn't be quite as difficult as it seems, since the bulk system Pathfinder 2e uses for inventory management doesn't need to be converted, and thus neither do the item weights. I'm guessing the biggest part would be changing the actor part of the conversion, since it's presumably different from D&D 5e's code-wise. That and the ranges of spells and abilities, and modifiying the automation of speed increasing abilities (the last part would be going above and beyond).

If you decide to do this, ideally it would come with a change to the diagonal rules. Since it's 2m squares, it's nice to have 3m diagonals instead of alternating between 2m and 4m. This is a good tip for 5e too. I didn't see it on the list of features and it's a great one.

I know it's a big ask, and don't feel obligated. Just wanted to let you know that there is demand, and I'd be forever grateful.

**Comment by HadaIonut** [comment]
Yeah, I would like to support pathfinder 2e but sadly I am so unfamiliar with the system I wouldn't know where to start. For example I didn't know that it has speed changing automations, those are generally incredibly difficult to work with (depending on how they are implemented), but maybe after I am done with my exams I will take a shot at that.

I am not sure what you mean by modifying diagonals, what I do at the moment is make the map be made of 1.5 m squares (for the default settings) and let the normal calculator to the work and it seemed to work fine for me. If you can elaborate on what you think is wrong with diagonals please do

**Comment by pearcebasmanm** [comment]
The speed changing automation generally takes the form of Rule Elements, which are a Pathfinder 2e feature similar to Active Effects (which is also has). They look something like this:
```json
{
    "key": "PF2E.RuleElement.BaseSpeed",
    "selector": "fly",
    "value": 30
}
```
(gives a fly speed of 30 feet)
or this:
```json
{
    "key":"PF2E.RuleElement.FlatModifier",
    "label":"Fleet",
    "selector":"speed",
    "type":"status",
    "value":5
}
```
(gives a 5 foot bonus to all move speeds).
I as a non-coder can understand this, so I imagine that you can. The only difficulty would be if it can recognise the "speed", "land-speed", "burrow-speed", "climb-speed", "fly-speed", or "swim-speed" selectors, and change the value only in those cases.

Converting automation isn't necessary, as it's easily done manually when adding the feats/features. I'd especially be remiss to see the conversion not happen for lack of a way to convert the automation.

For diagonals, I said 2 meters since there was a stream (can't find it for the life of me) in which someone who made the system mentioned that they were considering having 2 meter squares, and having diagonals be 3 meters. That way it would be round numbers and they could do away with the 5-10-5-10 rule. In my view that would be the main benifit of using metric, in addition to the objectively better measuring system.

**Comment by HadaIonut** [comment]
I see how automation works, it will take some time but I think I can also make that be converted.

About that diagonals thing, it is a bit beyond the scope of this module because having diagonals be anything other then the line * sqrt(2) will be a math fueled nightmare.

**Comment by pearcebasmanm** [comment]
Thanks! Take all the time you need.

I understand if it isn't something you'd like this module to do, but is 3 more difficult to program then 2√2? Or in the general case isn't 1.5x simpler than 1.4142...x?

**Comment by HadaIonut** [comment]
Well I am not sure how foundry computes distances but to get 3 instead of 2*1.4142 you would have to measure a different surface or at least approximate the result to something more normal. 
In any case it seems like it requires me to modify core foundry code and that is a big pain to do and maintain, so I will kindly decline that feature.

Edit: I think I just remembered, foundry doesn't do diagonals as line * sqrt(2), it just decides that the diagonal is equal to the line. But that still is a nightmare if you want the map to be any other size other then 2m/square

**Comment by pearcebasmanm** [comment]
I'm fairly confident that diagonals are system-specific, with Pathfinder using the 5-10-5 rule and other systems using things like euclidian, manhattan, or equidiant diagonals. That doesn't necessarily make it any easier to change it.

In response to the edit, that's how D&D5e does it, but not how all systems do.

**Comment by HadaIonut** [comment]
Ok, didn't know that, I will keep that diagonals idea in mind and see if I can get it to work

**Comment by HadaIonut** [comment]
Heya, I have just released support for Pathfinder 2e :D so i will be closing this issue
