### ISSUE TITLE
conversion not working in some cases

### ISSUE THREAD

**Issue by hamachee** [HadaIonut/Foundry-mgl#17]
When there is no space between number and unit, conversion not working. Is it intended?

ex) 10ft > 10ft
ex) 10 ft > 3 m

and inch, mile conversion is just not working properly.

ex) 5 inch > 5 centimeter (only unit changes.)
ex) 10 mile > 10 mile 

lbs > kg is not working too. pound > kg is working fine anyway.

Additionally, I hope there could be an option for cm not centimeters. and kg, km.

**Comment by HadaIonut** [comment]
Heya I have fixed this and it will be available in the next update
