### ISSUE TITLE
Reverse convertion: is there a way to convert back to feet?

### ISSUE THREAD

**Issue by igorteuri** [HadaIonut/Foundry-mgl#2]
Hi there! Loved your module! Thanks for the great work.

I was wondering if it would be possible to convert items back to feet. 
It would be great to convert some compendiuns I made with the meter value, but under the feet tag. 

Is there a way to use the module this way?

**Comment by HadaIonut** [comment]
Hi, there is no way of converting back to imperial since the idea of my module is that you will never have to see imperial units again. 
But I am not sure what you want to do with those compendiums, if you can elaborate on that I can try to help

**Comment by igorteuri** [comment]
I don't plan to keep using imperial units hahha

My case is:
I created a lot of compendia (in my native language) where the units are already in meters, but all unit numbers are under the Feet field.

When I try to Metrify those items, the module change these numbers because it recognizes that they're feet. So I get wrong numbers in the end, because it is converting 2 times (since I had already done it manually).

I wanted to be able to convert to imperial units in order to reconvert it to meters afterwards. This way I could keep my manually translated items.

I know it is a very specific scenario, but I have made A LOT of compendia in portuguese for my players hahhahaha

I don't know if it's possible to help me, but I thank you anyway. And again, thanks for your amazing job with the module. It is amazing. Wish I knew it before I made all those items.

**Comment by HadaIonut** [comment]
There is a manual way to do it.

As long as all the items you made are in compendiums that only contain other items that are in metric you could manually convert all the other compendiums and leave the ones you made untouched.

Or another option is to do a batch conversion of all the compendiums and delete the ones that have wrong values in them.

**Comment by igorteuri** [comment]
Yeah, I think the only way is to make it manually. 
I was looking for the reverse convertion because I wanted to have the correct values in a "meters" label (which foundry doesn't provide natively). 

But thanks anyway. 
You made an awesome job in this module. Metrifier is incredible!

**Comment by HadaIonut** [comment]
Hmm so you still have labels that need converting, could you please provide me with the export of such an item maybe i should provide a thing to just convert the labels

Also maybe add me on discord so I can see your messages faster assassinduke#0983

**Comment by igorteuri** [comment]
Of couse, I'll send you the export on discord. Thanks!
