### ISSUE TITLE
Conversion simply does not work

### ISSUE THREAD

**Issue by S4kr0s** [HadaIonut/Foundry-mgl#23]
Hi, I installed foundryVTT yesterday, installed this addon too (tested it with v9 and v10 of foundryVTT) and when I try to batch-convert the compendiums it just throws the following error for every compendium and does nothing: 
![Link](https://user-images.githubusercontent.com/32752372/187886812-971d8360-3ecc-400a-8f9c-d827bfe0e673.png)

**Comment by S4kr0s** [comment]
Starting as admin seems to solve the problem, that wasn't explained anywhere but it works now.

**Comment by S4kr0s** [comment]
Okay, the conversion seemed to be done, but every compendium with "Metrified" attached to the name is empty. After looking in the console, the following error came up:

Compendium5eConverter.js:134 TypeError: relinkTypeMap[type] is not a function
    at relinkTypeSelector (Compendium5eConverter.js:109)
    at relinkCompendium (Compendium5eConverter.js:120)
    at async relinkCompendiums (Compendium5eConverter.js:131)
    at async Dnd5eConverterNew.js:134

**Comment by HadaIonut** [comment]
Hi, i just released an update that makes this module functional for foundry 10. But this will most likely be the last update, i don't plan on supporting any of my foundry modules.

From what i have heard someone called Ethanks (on discord) is currently working on a replacement for this module, so in the future i suggest moving to that.
