### ISSUE TITLE
Compatibility problem with Mars 5e for batch compedium conversion

### ISSUE THREAD

**Issue by Naitbit** [HadaIonut/Foundry-mgl#4]
Converting whole compendium (or all of them at once), does not seem to work.
There is a progress and metrified compendiums are created, but they seem to be an exact copy of SRD compendiums (just editable and with metrified in name).
Metrifying spells/items manually does work though.

Foundry VTT v0.7.8
DnD 5e v1.2.2
![image](https://user-images.githubusercontent.com/4226039/104092989-6abc9480-527f-11eb-9f38-4c83798a13ec.png)

No errors in the console.

I did also try it on tiny new compendium with just 3 items, but it failed also there (I've checked that all 3 convert just fine individually)

Are there any steps I can do to debug/provide more data?

**Comment by HadaIonut** [comment]
Hi, I am not sure what is causing that problem, can you try to provide me with an export of the world that you are using?

Also if you disable all mods except foundry-mgl is the problem reproducible? You can give me a message on discord assassinduke#0983.

**Comment by Naitbit** [comment]
Sorry you are right, it was caused by incompatibility with Mars 5e https://foundryvtt.com/packages/mars-5e/

**Comment by HadaIonut** [comment]
If you want, you can disable mars, convert the stuff you need then disable my module and enable mars again, but I will look into it for a better fix

**Comment by Naitbit** [comment]
Should be fixed in https://github.com/HadaIonut/Foundry-mgl/releases/tag/v1.1.1
