### ISSUE TITLE
Feature request: Hide Metrify button in Combat Tracker popup

### ISSUE THREAD

**Issue by Naitbit** [HadaIonut/Foundry-mgl#6]
![obraz](https://user-images.githubusercontent.com/4226039/104243459-8038e680-5458-11eb-859b-5c8696734f75.png)
Combat tracker has metrify button hidden by default, but if ones right clicks to pop it up (to fe: see chat and popup at the same time) then the Metrify button appears occupying a lot of space.

**Comment by HadaIonut** [comment]
Oh, that didn't happen before. I think foundry got updated and an oversight on my side made that button appear.

Thx for letting me know

**Comment by Naitbit** [comment]
Not sure why, but it is back in 
Metrify 1.1.1, Foundry 0.7.9
![obraz](https://user-images.githubusercontent.com/4226039/107890186-5ec39280-6f0f-11eb-8617-12183bb2d05d.png)

ID's seem fine though:
![obraz](https://user-images.githubusercontent.com/4226039/107890143-45224b00-6f0f-11eb-93f4-6b9220159f55.png)

Should I open new issue?

**Comment by HadaIonut** [comment]
Try updating the module, the latest build is 1.1.2 and it doesn't seem to have this issue. 

It the buttons are still there make a new issue
