### ISSUE TITLE
Hide Metrify button in Playlist Directory popup

### ISSUE THREAD

**Issue by Naitbit** [HadaIonut/Foundry-mgl#8]
Playlist Directory displays a Metrify button that is not useful
Related to (but different window, I don't see it Combat Tracker anymore) : https://github.com/HadaIonut/Foundry-mgl/issues/6

![obraz](https://user-images.githubusercontent.com/4226039/108270162-fb33a200-7166-11eb-8a5e-8f781724b90f.png)

module version 1.1.2
![obraz](https://user-images.githubusercontent.com/4226039/108270234-169ead00-7167-11eb-862d-72b2287e1e09.png)

**Comment by HadaIonut** [comment]
Oh, I completely forgot that other popouts exist... I'll fix them soon

**Comment by HadaIonut** [comment]
I have decided to remove the batch convert button from the popouts since they look pretty bad there.
